export const DEFAULT_GREETINGS = [
  "Let's make today unforgettable.",
  "You're closer than you think — keep going.",
  "Big energy, big moves. Start now.",
  "Something awesome is about to happen.",
  "Your future self is cheering you on.",
  "Ready when you are — let's build.",
  "Small steps, massive momentum.",
  "Today is a great day to level up.",
  "You've got this. Seriously.",
  "Turn ideas into action.",
  "Make it happen — one tab at a time.",
  "The best time to start was yesterday. The next best is now.",
  "Bring the heat today.",
  "You're capable of more than you know.",
  "Focus up — great things ahead.",
  "Let's turn potential into progress.",
  "Your vibe attracts your tribe. Stay bold.",
  "Dream big, move fast, stay curious.",
  "Every new tab is a fresh start.",
  "Confidence looks good on you.",
  "Go create something you're proud of.",
  "The world needs what you're building.",
  "Stay hungry, stay kind, stay moving.",
  "Make today count.",
  "Let's go — the adventure continues.",
  "Rise up — today's yours to win.",
  "Momentum is a superpower. Use it.",
  "You're one bold move away from magic.",
  "Keep pushing — breakthroughs love persistence.",
  "Your energy sets the tone. Make it fire.",
  "Show up like you mean it.",
  "Greatness starts with showing up.",
  "You're building something that matters.",
  "Don't wait for perfect — start now.",
  "Your ambition is your fuel.",
  "Make waves, not excuses.",
  "Today's the day to surprise yourself.",
  "You're stronger than yesterday.",
  "Keep your head up and your standards higher.",
  "Progress beats perfection every time.",
  "You're writing a comeback story.",
  "Stay locked in — you're on the right track.",
  "Turn up the volume on your dreams.",
  "You were built for moments like this.",
  "Keep stacking wins, no matter how small.",
  "Your hustle is inspiring — keep going.",
  "Believe in the version of you that's coming.",
  "You're not behind — you're building.",
  "Make bold choices. Live boldly.",
  "The grind today becomes the glow-up tomorrow.",
  "You're allowed to be proud of how far you've come.",
  "Keep moving — clarity follows action.",
  "Your potential is loud. Let it out.",
  "Today's a canvas — paint something wild.",
  "You don't need permission to go all in.",
  "Stay curious, stay fearless, stay you.",
  "You're closer to the finish line than it feels.",
  "Make your future self proud today.",
  "Energy in, results out. Let's go.",
  "You're doing better than you think.",
  "Keep the faith — the payoff is coming.",
  "Your story is still being written. Make it epic.",
  "No cap — you're built different.",
  "Turn pressure into power.",
  "You're the main character today. Act like it.",
  "Keep showing up — that's the whole secret.",
  "Your dreams deserve your full effort.",
  "Stay in the game — winners don't quit.",
  "You're planting seeds for something huge.",
  "Make today feel like a victory lap.",
  "Your focus is your superpower.",
  "Keep climbing — the view gets better.",
  "You're allowed to want more and go get it.",
  "Turn setbacks into comebacks.",
  "Your light is needed out there.",
  "Stay dangerous — in the best way.",
  "You're one session away from a breakthrough.",
  "Keep your standards high and your head clear.",
  "Make noise with your work, not your words.",
  "You're evolving faster than you realize.",
  "Stay patient, stay hungry, stay ready.",
  "Your best chapter starts now.",
  "Keep betting on yourself — it's paying off.",
  "You're not stuck — you're gearing up.",
  "Make today impossible to forget.",
  "Your courage is contagious — spread it.",
  "Stay relentless — good things take grit.",
  "You're crafting a life worth living.",
  "Keep the momentum — don't look back.",
  "Your ideas deserve to see daylight.",
  "Stay sharp, stay soft, stay moving.",
  "You're winning quietly — keep going.",
  "Make space for something amazing today.",
  "Your drive is your edge.",
  "Keep building — brick by brick.",
  "You're exactly where you need to be to start.",
  "You're proof that effort compounds.",
  "Stay wild about your goals.",
  "Your time is now — own it.",
  "Keep running your race.",
  "You're building momentum that can't be stopped.",
  "Stay fearless in pursuit of what fires you up.",
  "Your growth is showing — keep watering it.",
  "Make today feel like a launch day.",
  "Keep going — you're almost there.",
];
